[package]
name = "keybswitch"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
udev = "0.8"
xkbcommon = "0.7.0"
which = "6.0.1"
xdg = "2.5.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
